# Generated by Django 5.2.5 on 2026-01-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0007_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_key',
            field=models.CharField(default='exit', max_length=50),
            preserve_default=False,
        ),
    ]
