# Generated by Django 5.2.5 on 2026-01-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0008_product_image_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='image_key',
            field=models.CharField(default='exit', max_length=50),
            preserve_default=False,
        ),
    ]
