# Generated by Django 5.2.5 on 2026-01-26 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0009_cartitem_image_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='image_key',
        ),
    ]
